# Generated by Django 5.2.4 on 2026-01-14 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('school_name', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdeaSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(help_text='Detailed description of your idea')),
                ('problem_statement', models.TextField(help_text='What problem does your idea solve?')),
                ('target_audience', models.TextField(help_text='Who will benefit from your idea?')),
                ('innovation_aspect', models.TextField(help_text='What makes your idea innovative?')),
                ('implementation_plan', models.TextField(help_text='How do you plan to implement this idea?')),
                ('impact_assessment', models.TextField(help_text='What impact will your idea have?')),
                ('ai_suggested_category', models.CharField(blank=True, choices=[('edtech', 'EdTech'), ('sustainability', 'Sustainability'), ('health', 'Health & Wellness'), ('fintech', 'FinTech'), ('social_impact', 'Social Impact'), ('agriculture', 'Agriculture'), ('technology', 'Technology'), ('entertainment', 'Entertainment'), ('other', 'Other')], max_length=50)),
                ('final_category', models.CharField(blank=True, choices=[('edtech', 'EdTech'), ('sustainability', 'Sustainability'), ('health', 'Health & Wellness'), ('fintech', 'FinTech'), ('social_impact', 'Social Impact'), ('agriculture', 'Agriculture'), ('technology', 'Technology'), ('entertainment', 'Entertainment'), ('other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('reviewed', 'Reviewed')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_processed', models.BooleanField(default=False)),
                ('ai_processing_error', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='students.student')),
            ],
            options={
                'ordering': ['-submitted_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('document', 'Document/PPT'), ('image', 'Image'), ('video', 'Video')], max_length=20)),
                ('file', models.FileField(upload_to='submissions/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_text', models.TextField(blank=True, help_text='Text extracted from file for AI analysis')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='students.ideasubmission')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ideasubmission',
            index=models.Index(fields=['status', '-submitted_at'], name='students_id_status_f37d8d_idx'),
        ),
        migrations.AddIndex(
            model_name='ideasubmission',
            index=models.Index(fields=['student', '-created_at'], name='students_id_student_c77a6b_idx'),
        ),
    ]
