# Generated by Django 5.2.4 on 2026-01-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideasubmission',
            name='feasibility_execution',
            field=models.TextField(blank=True, default='', help_text='How realistically can this idea be implemented? What resources, technology, and effort are needed?'),
        ),
        migrations.AddField(
            model_name='ideasubmission',
            name='idea_stage',
            field=models.CharField(choices=[('idea', 'Idea'), ('concept_prototype', 'Concept Prototype'), ('working_prototype', 'Working Prototype'), ('running_business', 'Running Business Idea')], default='idea', help_text='Current development stage of your idea', max_length=30),
        ),
        migrations.AddField(
            model_name='ideasubmission',
            name='impact_usefulness',
            field=models.TextField(blank=True, default='', help_text='What is the potential benefit, scale, or value of your idea? Who will benefit and how much?'),
        ),
        migrations.AddField(
            model_name='ideasubmission',
            name='innovation_uniqueness',
            field=models.TextField(blank=True, default='', help_text='How is your idea different from existing solutions? What makes it unique or innovative?'),
        ),
        migrations.AddField(
            model_name='ideasubmission',
            name='proposed_solution',
            field=models.TextField(blank=True, default='', help_text='How does your idea solve this problem? Explain your solution approach.'),
        ),
        migrations.AlterField(
            model_name='ideasubmission',
            name='description',
            field=models.TextField(blank=True, help_text='[Legacy] Detailed description of your idea'),
        ),
        migrations.AlterField(
            model_name='ideasubmission',
            name='impact_assessment',
            field=models.TextField(blank=True, help_text='[Legacy] What impact will your idea have?'),
        ),
        migrations.AlterField(
            model_name='ideasubmission',
            name='implementation_plan',
            field=models.TextField(blank=True, help_text='[Legacy] How do you plan to implement this idea?'),
        ),
        migrations.AlterField(
            model_name='ideasubmission',
            name='innovation_aspect',
            field=models.TextField(blank=True, help_text='[Legacy] What makes your idea innovative?'),
        ),
        migrations.AlterField(
            model_name='ideasubmission',
            name='problem_statement',
            field=models.TextField(help_text='What problem is being solved and for whom? Describe the problem clearly and identify your target audience.'),
        ),
        migrations.AlterField(
            model_name='ideasubmission',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('evaluated', 'Evaluated'), ('reviewed', 'Reviewed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='ideasubmission',
            name='target_audience',
            field=models.TextField(blank=True, help_text='[Legacy] Who will benefit from your idea?'),
        ),
        migrations.AlterField(
            model_name='ideasubmission',
            name='title',
            field=models.CharField(help_text='Give your idea a clear, descriptive title', max_length=300),
        ),
    ]
