# Generated by Django 5.2.4 on 2026-01-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_ideasubmission_feasibility_execution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideasubmission',
            name='problem_definition',
            field=models.TextField(blank=True, default='', help_text="It's always better to define the problem before we attempt to solve it. Be précised in articulating it."),
        ),
        migrations.AddField(
            model_name='ideasubmission',
            name='problem_description',
            field=models.TextField(blank=True, default='', help_text='Give us a detailed description of the problem.'),
        ),
        migrations.AddField(
            model_name='ideasubmission',
            name='problem_urgency',
            field=models.TextField(blank=True, default='', help_text='Why do you believe that this problem is critical and needs an urgent solution?'),
        ),
        migrations.AddField(
            model_name='ideasubmission',
            name='solution',
            field=models.TextField(blank=True, default='', help_text='What is your solution?'),
        ),
        migrations.AddField(
            model_name='ideasubmission',
            name='solution_benefits',
            field=models.TextField(blank=True, default='', help_text='How your solution gives a distinct benefit to users or reduce their pain?'),
        ),
        migrations.AddField(
            model_name='ideasubmission',
            name='target_user_group',
            field=models.TextField(blank=True, default='', help_text="Describe the 'user' group whose problem you are attempting to solve?"),
        ),
        migrations.AddField(
            model_name='ideasubmission',
            name='why_best_equipped',
            field=models.TextField(blank=True, default='', help_text='Why do you think you are the best equipped to offer this solution?'),
        ),
        migrations.AlterField(
            model_name='ideasubmission',
            name='feasibility_execution',
            field=models.TextField(blank=True, help_text='[Legacy] Feasibility execution'),
        ),
        migrations.AlterField(
            model_name='ideasubmission',
            name='idea_stage',
            field=models.CharField(choices=[('idea', 'Idea'), ('concept_prototype', 'Concept Prototype'), ('working_prototype', 'Working Prototype'), ('running_business', 'Running Business Idea')], default='idea', help_text='Mention the stage of your idea at this moment', max_length=30),
        ),
        migrations.AlterField(
            model_name='ideasubmission',
            name='impact_usefulness',
            field=models.TextField(blank=True, help_text='[Legacy] Impact usefulness'),
        ),
        migrations.AlterField(
            model_name='ideasubmission',
            name='innovation_uniqueness',
            field=models.TextField(blank=True, help_text='[Legacy] Innovation uniqueness'),
        ),
        migrations.AlterField(
            model_name='ideasubmission',
            name='problem_statement',
            field=models.TextField(blank=True, help_text='[Legacy] Problem statement'),
        ),
        migrations.AlterField(
            model_name='ideasubmission',
            name='proposed_solution',
            field=models.TextField(blank=True, help_text='[Legacy] Proposed solution'),
        ),
        migrations.AlterField(
            model_name='ideasubmission',
            name='title',
            field=models.CharField(blank=True, help_text='[Legacy] Idea title', max_length=300),
        ),
    ]
