# Generated by Django 5.2.4 on 2026-02-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_ideasubmission_problem_definition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideasubmission',
            name='ai_suggested_category',
            field=models.CharField(blank=True, choices=[('edtech', 'EdTech'), ('sustainability', 'Sustainability'), ('health', 'Health & Wellness'), ('fintech', 'FinTech'), ('social_impact', 'Social Impact'), ('agriculture', 'Agriculture'), ('technology', 'Technology'), ('entertainment', 'Entertainment'), ('other', 'Other'), ('incoherent', 'Incoherent')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ideasubmission',
            name='final_category',
            field=models.CharField(blank=True, choices=[('edtech', 'EdTech'), ('sustainability', 'Sustainability'), ('health', 'Health & Wellness'), ('fintech', 'FinTech'), ('social_impact', 'Social Impact'), ('agriculture', 'Agriculture'), ('technology', 'Technology'), ('entertainment', 'Entertainment'), ('other', 'Other'), ('incoherent', 'Incoherent')], max_length=50),
        ),
    ]
