# Generated by Django 5.2.4 on 2026-02-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_ideasubmission_ai_suggested_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideasubmission',
            name='q10_feedback',
            field=models.TextField(blank=True, default='', help_text='Have you taken any user feedback? Describe one situation where your thinking changed after feedback.'),
        ),
        migrations.AddField(
            model_name='ideasubmission',
            name='q11_creative_element',
            field=models.TextField(blank=True, default='', help_text='What is the most creative or unexpected element in your solution, and why did you think of it?'),
        ),
        migrations.AddField(
            model_name='ideasubmission',
            name='q12_pitch',
            field=models.TextField(blank=True, default='', help_text='If you had 60 seconds to convince someone to try or support your idea, what would you say?'),
        ),
        migrations.AddField(
            model_name='ideasubmission',
            name='q1_target_group',
            field=models.TextField(blank=True, default='', help_text="Describe the person/group you're trying to help. Who are they, what is their daily struggle?"),
        ),
        migrations.AddField(
            model_name='ideasubmission',
            name='q2_exact_problem',
            field=models.TextField(blank=True, default='', help_text='What exact problem are they facing? When, where, and why does this problem matter?'),
        ),
        migrations.AddField(
            model_name='ideasubmission',
            name='q3_solution_simple',
            field=models.TextField(blank=True, default='', help_text='What is your solution, explained simply as if talking to a 10-year-old?'),
        ),
        migrations.AddField(
            model_name='ideasubmission',
            name='q4_differentiation',
            field=models.TextField(blank=True, default='', help_text='How is your solution different from what already exists?'),
        ),
        migrations.AddField(
            model_name='ideasubmission',
            name='q5_build_steps',
            field=models.TextField(blank=True, default='', help_text='What are the key steps required to build and test your solution?'),
        ),
        migrations.AddField(
            model_name='ideasubmission',
            name='q6_resources',
            field=models.TextField(blank=True, default='', help_text='What resources (skills, tools, money, tech, people) are required? Which do you already have?'),
        ),
        migrations.AddField(
            model_name='ideasubmission',
            name='q7_positive_change',
            field=models.TextField(blank=True, default='', help_text='If your solution succeeds, what positive change will it create for users and society?'),
        ),
        migrations.AddField(
            model_name='ideasubmission',
            name='q8_challenges',
            field=models.TextField(blank=True, default='', help_text='What challenges could come while building or using this idea? How will you deal with them?'),
        ),
        migrations.AddField(
            model_name='ideasubmission',
            name='q9_team_fit',
            field=models.TextField(blank=True, default='', help_text='Why do you think your team is rightly placed to solve this problem?'),
        ),
        migrations.AlterField(
            model_name='ideasubmission',
            name='idea_stage',
            field=models.CharField(choices=[('idea', 'Idea'), ('concept_prototype', 'Concept Prototype'), ('working_prototype', 'Working Prototype'), ('running_business', 'Running Business Idea')], default='idea', help_text='[Legacy-v2] Idea stage', max_length=30),
        ),
        migrations.AlterField(
            model_name='ideasubmission',
            name='problem_definition',
            field=models.TextField(blank=True, default='', help_text='[Legacy-v2] Problem definition'),
        ),
        migrations.AlterField(
            model_name='ideasubmission',
            name='problem_description',
            field=models.TextField(blank=True, default='', help_text='[Legacy-v2] Detailed problem description'),
        ),
        migrations.AlterField(
            model_name='ideasubmission',
            name='problem_urgency',
            field=models.TextField(blank=True, default='', help_text='[Legacy-v2] Problem urgency'),
        ),
        migrations.AlterField(
            model_name='ideasubmission',
            name='solution',
            field=models.TextField(blank=True, default='', help_text='[Legacy-v2] Solution'),
        ),
        migrations.AlterField(
            model_name='ideasubmission',
            name='solution_benefits',
            field=models.TextField(blank=True, default='', help_text='[Legacy-v2] Solution benefits'),
        ),
        migrations.AlterField(
            model_name='ideasubmission',
            name='target_user_group',
            field=models.TextField(blank=True, default='', help_text='[Legacy-v2] Target user group'),
        ),
        migrations.AlterField(
            model_name='ideasubmission',
            name='why_best_equipped',
            field=models.TextField(blank=True, default='', help_text='[Legacy-v2] Why best equipped'),
        ),
    ]
