# Generated by Django 5.2.4 on 2026-03-30 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_ideasubmission_q10_feedback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('grade', models.CharField(blank=True, max_length=20)),
                ('school_name', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(choices=[('leader', 'Team Leader'), ('member', 'Member')], default='member', max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='students.ideasubmission')),
            ],
            options={
                'ordering': ['role', 'name'],
            },
        ),
    ]
