# Generated by Django 5.2.4 on 2026-05-29 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_school'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('inactive', 'Inactive'), ('active', 'Active')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.school'),
        ),
        migrations.AlterField(
            model_name='school',
            name='board',
            field=models.CharField(blank=True, choices=[('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('SSC', 'SSC'), ('IB', 'IB'), ('IGCSE', 'IGCSE'), ('Other', 'Other')], max_length=10),
        ),
    ]
