# Generated by Django 5.2.4 on 2026-06-01 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_team_teammembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembership',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='students.student'),
        ),
    ]
