# Generated by Django 5.2.4 on 2026-06-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_school_affiliation_number_school_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideasubmission',
            name='competition_track',
            field=models.CharField(blank=True, choices=[('sustainable-energy', 'Sustainable Energy'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('fintech', 'FinTech'), ('agriculture', 'Agriculture'), ('smart-cities', 'Smart Cities')], max_length=30),
        ),
    ]
