# Generated by Django 5.2.16 on 2026-08-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0025_school_google_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='activation_checklist',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
