# Generated by Django 5.2.16 on 2026-08-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0026_school_activation_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='coordinator_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='school',
            name='coordinator_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='school',
            name='ift_teacher_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='school',
            name='ift_teacher_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
