# Generated by Django 5.2.16 on 2026-08-24 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0027_school_coordinator_email_school_coordinator_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='ift_teacher_email',
        ),
        migrations.RemoveField(
            model_name='school',
            name='ift_teacher_name',
        ),
    ]
