# Generated by Django 5.2.16 on 2026-08-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0028_remove_school_ift_teacher_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='has_seen_welcome_popup',
            field=models.BooleanField(default=False),
        ),
    ]
