# Generated by Django 5.2.16 on 2026-09-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0030_school_utm_campaign_school_utm_medium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='has_seen_deadline_extended_popup',
            field=models.BooleanField(default=False),
        ),
    ]
