# Generated by Django 5.2.4 on 2026-03-30 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0006_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jury_name', models.CharField(max_length=200)),
                ('jury_org', models.CharField(blank=True, help_text='Organisation / Institution', max_length=200)),
                ('assigned_on', models.DateField(blank=True, null=True)),
                ('evaluated_on', models.DateField(blank=True, null=True)),
                ('jury_score', models.IntegerField(blank=True, help_text='Score given by jury (0-100)', null=True)),
                ('notes', models.TextField(blank=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_assignments', to='students.ideasubmission')),
            ],
            options={
                'ordering': ['-assigned_on'],
            },
        ),
    ]
