# Generated by Django 5.2.4 on 2026-05-29 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
        ('students', '0008_school_status_school_user_student_school_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluatorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('evaluated', 'Evaluated')], default='assigned', max_length=20)),
                ('assigned_on', models.DateTimeField(auto_now_add=True)),
                ('evaluated_on', models.DateTimeField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, help_text='Manual evaluation score (0-100)', null=True)),
                ('notes', models.TextField(blank=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluator_assignments', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluator_assignments', to='students.ideasubmission')),
            ],
            options={
                'ordering': ['-assigned_on'],
                'unique_together': {('evaluator', 'submission')},
            },
        ),
    ]
