# Generated by Django 5.2.4 on 2026-06-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='content',
            name='tags',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='content',
            name='visibility',
            field=models.CharField(choices=[('all', 'All Users'), ('students', 'Students Only'), ('evaluators', 'Evaluators Only'), ('schools', 'Schools Only'), ('admins', 'Admins Only')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
    ]
