# Generated by Django 5.2.4 on 2026-06-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluatorassignment',
            name='parameter_scores',
            field=models.JSONField(blank=True, default=dict, help_text='Dict of parameter: score'),
        ),
        migrations.AlterField(
            model_name='evaluatorassignment',
            name='score',
            field=models.IntegerField(blank=True, help_text='Manual evaluation score (0-50)', null=True),
        ),
    ]
