# Generated by Django 5.2.4 on 2026-06-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_evaluatorassignment_parameter_scores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluatorassignment',
            name='is_shortlisted',
            field=models.BooleanField(default=False),
        ),
    ]
