# Generated by Django 5.2.16 on 2026-08-03 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0011_digitalresource'),
        ('students', '0025_school_google_place_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.CharField(choices=[('idea_reminder', 'Idea Submission Reminder'), ('idea_published', 'Idea Published'), ('top400', 'Top 400 Announcement'), ('resubmit_reminder', 'Resubmit Reminder'), ('school_winner', 'School Winner Announcement'), ('top100', 'Top 100 Announcement'), ('zonal_pitch', 'Zonal Pitch Fest Invite'), ('top12', 'Top 12 Announcement')], max_length=30)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_emails', to='students.student')),
            ],
            options={
                'ordering': ['-sent_at'],
                'unique_together': {('student', 'milestone')},
            },
        ),
    ]
