# Generated by Django 5.2.16 on 2026-08-03 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0012_milestoneemaillog'),
        ('students', '0025_school_google_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestoneemaillog',
            name='milestone',
            field=models.CharField(choices=[('idea_reminder', 'Idea Submission Reminder'), ('idea_published', 'Idea Published'), ('top400', 'Top 400 Announcement'), ('resubmit_reminder', 'Resubmit Reminder'), ('school_winner', 'School Winner Announcement'), ('top100', 'Top 100 Announcement'), ('zonal_pitch', 'Zonal Pitch Fest Invite'), ('top12', 'Top 12 Announcement'), ('hall_of_fame', 'Hall of Fame / Pitch Ticket')], max_length=30),
        ),
        migrations.CreateModel(
            name='RecurringEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_key', models.CharField(max_length=50)),
                ('sent_date', models.DateField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_emails', to='students.school')),
            ],
            options={
                'ordering': ['-sent_date'],
                'unique_together': {('school', 'email_key', 'sent_date')},
            },
        ),
    ]
