# Generated by Django 5.2.16 on 2026-08-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0013_alter_milestoneemaillog_milestone_recurringemaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='live_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='content',
            name='reminder_notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
