# Generated by Django 5.2.16 on 2026-08-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0014_content_live_notification_sent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='digitalresource',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='digitalresource',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
