# Generated by Django 5.2.16 on 2026-08-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0016_seed_collateral_order_summaries'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_idea_booster_masterclass',
            field=models.BooleanField(default=False),
        ),
    ]
