# Generated by Django 5.2.4 on 2026-03-27 07:16

from django.db import migrations


def backfill_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('accounts', 'UserProfile')

    for user in User.objects.all():
        if UserProfile.objects.filter(user=user).exists():
            continue
        if user.is_superuser or user.is_staff:
            UserProfile.objects.create(user=user, role='superadmin')
        else:
            UserProfile.objects.create(user=user, role='student')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(backfill_profiles, migrations.RunPython.noop),
    ]
