# Generated by Django 5.2.4 on 2026-05-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_backfill_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('jury', 'Evaluator'), ('school', 'School'), ('superadmin', 'Super Admin')], default='student', max_length=20),
        ),
    ]
