# Generated by Django 5.2.4 on 2026-06-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='juryprofile',
            name='additional_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='juryprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='juryprofile',
            name='alternate_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='juryprofile',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='juryprofile',
            name='available_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='juryprofile',
            name='available_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='juryprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='juryprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='juryprofile',
            name='designation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='juryprofile',
            name='evaluation_mode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='juryprofile',
            name='evaluation_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='juryprofile',
            name='evaluation_season',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='juryprofile',
            name='experience',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='juryprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='juryprofile',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='juryprofile',
            name='jury_role',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='juryprofile',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='juryprofile',
            name='max_ideas_per_week',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='juryprofile',
            name='nationality',
            field=models.CharField(blank=True, default='Indian', max_length=100),
        ),
        migrations.AddField(
            model_name='juryprofile',
            name='pin_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='juryprofile',
            name='preferred_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='juryprofile',
            name='preferred_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='juryprofile',
            name='previous_jury_exp',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='juryprofile',
            name='qualification',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='juryprofile',
            name='secondary_expertise',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='juryprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='juryprofile',
            name='willing_to_bootcamp',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='juryprofile',
            name='willing_to_mentor',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
