# Generated by Django 5.2.15 on 2026-08-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_announcements_read_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('jury', 'Evaluator'), ('school', 'School'), ('superadmin', 'Super Admin'), ('viewer', 'Viewer (Read-only)')], default='student', max_length=20),
        ),
    ]
