# Generated by Django 5.2.15 on 2026-08-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('jury', 'Evaluator'), ('school', 'School'), ('superadmin', 'Super Admin'), ('viewer', 'Viewer (Read-only)'), ('tce', 'TCE (Read-only, limited)')], default='student', max_length=20),
        ),
    ]
