# Generated by Django 5.2.15 on 2026-08-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_ticket_merged_into_ticketevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
