# Generated by Django 5.2.4 on 2026-01-14 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(help_text='2-3 sentence neutral summary')),
                ('suggested_tags', models.JSONField(default=list, help_text='AI-suggested category tags')),
                ('is_complete', models.BooleanField(default=True)),
                ('completeness_notes', models.TextField(blank=True, help_text='Notes about missing information')),
                ('model_used', models.CharField(default='deepseek/deepseek-chat', max_length=100)),
                ('tokens_used', models.IntegerField(default=0)),
                ('processing_time', models.FloatField(default=0, help_text='Processing time in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_response', models.TextField(blank=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_summary', to='students.ideasubmission')),
            ],
            options={
                'verbose_name_plural': 'AI Summaries',
                'ordering': ['-created_at'],
            },
        ),
    ]
