# Generated by Django 5.2.4 on 2026-01-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisummary',
            name='file_summaries',
            field=models.JSONField(blank=True, default=dict, help_text='Summaries of uploaded file contents'),
        ),
        migrations.AddField(
            model_name='aisummary',
            name='inconsistency_reasons',
            field=models.JSONField(blank=True, default=list, help_text='Reasons why content may be inconsistent'),
        ),
        migrations.AddField(
            model_name='aisummary',
            name='is_consistent',
            field=models.BooleanField(default=True, help_text='Do uploaded files match the idea description?'),
        ),
    ]
