# Generated by Django 5.2.4 on 2026-01-20 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_aisummary_file_summaries_and_more'),
        ('students', '0002_ideasubmission_feasibility_execution_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_clarity_score', models.IntegerField(default=0, help_text='Problem Clarity & Relevance (max 20)')),
                ('innovation_score', models.IntegerField(default=0, help_text='Innovation / Uniqueness (max 20)')),
                ('feasibility_score', models.IntegerField(default=0, help_text='Feasibility & Practicality (max 20)')),
                ('impact_score', models.IntegerField(default=0, help_text='Impact & Usefulness (max 15)')),
                ('explanation_quality_score', models.IntegerField(default=0, help_text='Clarity of Solution Explanation (max 15)')),
                ('idea_maturity_score', models.IntegerField(default=0, help_text='Idea Maturity Signal (max 10)')),
                ('final_score', models.IntegerField(default=0, help_text='Total score out of 100')),
                ('rank', models.IntegerField(blank=True, help_text='Position in overall ranking', null=True)),
                ('is_top_400', models.BooleanField(default=False, help_text='Selected in Top 400')),
                ('problem_clarity_justification', models.TextField(blank=True)),
                ('innovation_justification', models.TextField(blank=True)),
                ('feasibility_justification', models.TextField(blank=True)),
                ('impact_justification', models.TextField(blank=True)),
                ('explanation_quality_justification', models.TextField(blank=True)),
                ('idea_maturity_justification', models.TextField(blank=True)),
                ('overall_justification', models.TextField(blank=True, help_text='Overall evaluation summary')),
                ('confidence_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', help_text='AI confidence in this evaluation', max_length=10)),
                ('model_used', models.CharField(default='anthropic/claude-3.5-sonnet', max_length=100)),
                ('tokens_used', models.IntegerField(default=0)),
                ('processing_time', models.FloatField(default=0, help_text='Processing time in seconds')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('raw_response', models.TextField(blank=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_evaluation', to='students.ideasubmission')),
            ],
            options={
                'verbose_name_plural': 'AI Evaluations',
                'ordering': ['-final_score', '-problem_clarity_score', '-innovation_score'],
                'indexes': [models.Index(fields=['-final_score'], name='ai_assistan_final_s_c22274_idx'), models.Index(fields=['rank'], name='ai_assistan_rank_fc1797_idx')],
            },
        ),
    ]
