# Generated by Django 5.2.4 on 2026-01-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_aievaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='aievaluation',
            name='attachment_mismatch',
            field=models.BooleanField(default=False, help_text='Are attachments mismatched with idea?'),
        ),
        migrations.AddField(
            model_name='aievaluation',
            name='attachment_mismatch_reasons',
            field=models.JSONField(blank=True, default=list, help_text='Reasons for attachment mismatch'),
        ),
    ]
