# Generated by Django 5.2.4 on 2026-01-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0004_aievaluation_attachment_mismatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aievaluation',
            name='mismatch_severity',
            field=models.CharField(choices=[('none', 'None'), ('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='none', help_text='Severity of attachment mismatch: none, minor, moderate, severe', max_length=10),
        ),
    ]
