# Generated by Django 5.2.4 on 2026-02-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0006_new_10_parameter_rubric'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aievaluation',
            options={'ordering': ['-final_score', '-uniqueness_score', '-impactful_score'], 'verbose_name_plural': 'AI Evaluations'},
        ),
        migrations.AddField(
            model_name='aievaluation',
            name='is_coherent',
            field=models.BooleanField(default=True, help_text='Do all submission fields relate to the same idea?'),
        ),
        migrations.AlterField(
            model_name='aievaluation',
            name='conceptual_clarity_score',
            field=models.IntegerField(default=1, help_text='Conceptual Clarity & Comprehensiveness (1-5)'),
        ),
        migrations.AlterField(
            model_name='aievaluation',
            name='final_score',
            field=models.IntegerField(default=0, help_text='Total score out of 50'),
        ),
    ]
