# Generated by Django 5.2.4 on 2026-02-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0007_alter_aievaluation_options_aievaluation_is_coherent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aievaluation',
            name='communication_score',
            field=models.IntegerField(default=0, help_text='Communication (0-5, 0=incoherent)'),
        ),
        migrations.AlterField(
            model_name='aievaluation',
            name='conceptual_clarity_score',
            field=models.IntegerField(default=0, help_text='Conceptual Clarity & Comprehensiveness (0-5, 0=incoherent)'),
        ),
        migrations.AlterField(
            model_name='aievaluation',
            name='creativity_score',
            field=models.IntegerField(default=0, help_text='Creativity (0-5, 0=incoherent)'),
        ),
        migrations.AlterField(
            model_name='aievaluation',
            name='ease_of_implementation_score',
            field=models.IntegerField(default=0, help_text='Ease of Implementation (0-5, 0=incoherent)'),
        ),
        migrations.AlterField(
            model_name='aievaluation',
            name='empathy_score',
            field=models.IntegerField(default=0, help_text='Empathy (0-5, 0=incoherent)'),
        ),
        migrations.AlterField(
            model_name='aievaluation',
            name='flexible_thinking_score',
            field=models.IntegerField(default=0, help_text='Flexible Thinking (0-5, 0=incoherent)'),
        ),
        migrations.AlterField(
            model_name='aievaluation',
            name='impactful_score',
            field=models.IntegerField(default=0, help_text='Impactful (0-5, 0=incoherent)'),
        ),
        migrations.AlterField(
            model_name='aievaluation',
            name='scalable_score',
            field=models.IntegerField(default=0, help_text='Scalable (0-5, 0=incoherent)'),
        ),
        migrations.AlterField(
            model_name='aievaluation',
            name='sustainable_score',
            field=models.IntegerField(default=0, help_text='Sustainable (0-5, 0=incoherent)'),
        ),
        migrations.AlterField(
            model_name='aievaluation',
            name='uniqueness_score',
            field=models.IntegerField(default=0, help_text='Uniqueness (0-5, 0=incoherent)'),
        ),
    ]
