# Generated by Django 5.2.4 on 2026-02-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0008_alter_aievaluation_communication_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aievaluation',
            name='attachment_mismatch',
            field=models.BooleanField(default=False, help_text='Are attachments mismatched with idea?'),
        ),
        migrations.AddField(
            model_name='aievaluation',
            name='mismatch_penalty',
            field=models.IntegerField(default=0, help_text='Marks deducted for attachment mismatch'),
        ),
        migrations.AddField(
            model_name='aievaluation',
            name='mismatch_reasons',
            field=models.JSONField(blank=True, default=list, help_text='Reasons for attachment mismatch'),
        ),
        migrations.AddField(
            model_name='aievaluation',
            name='mismatch_severity',
            field=models.CharField(choices=[('none', 'None'), ('minor', 'Minor Mismatch'), ('severe', 'Severe Mismatch'), ('missing', 'No Attachments')], default='none', max_length=10),
        ),
    ]
