# Generated by Django 5.2.4 on 2026-02-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0009_aievaluation_attachment_mismatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aievaluation',
            name='attachment_summaries',
            field=models.JSONField(blank=True, default=dict, help_text='Per-file analysis: summaries, relevance, missing types'),
        ),
    ]
