# Generated by Django 5.2.4 on 2026-02-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0010_add_attachment_summaries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aievaluation',
            name='scalable_justification',
        ),
        migrations.RemoveField(
            model_name='aievaluation',
            name='scalable_score',
        ),
        migrations.AddField(
            model_name='aievaluation',
            name='coherence_checks',
            field=models.JSONField(blank=True, default=dict, help_text='Results of 10 coherence cross-checks'),
        ),
        migrations.AddField(
            model_name='aievaluation',
            name='coherence_failures',
            field=models.IntegerField(default=0, help_text='Number of failed coherence checks (0-10)'),
        ),
        migrations.AddField(
            model_name='aievaluation',
            name='feasibility_justification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aievaluation',
            name='feasibility_score',
            field=models.IntegerField(default=0, help_text='Feasibility (0-10)'),
        ),
        migrations.AddField(
            model_name='aievaluation',
            name='is_disqualified',
            field=models.BooleanField(default=False, help_text='True if >5 coherence checks failed (score=0)'),
        ),
        migrations.AlterField(
            model_name='aievaluation',
            name='communication_score',
            field=models.IntegerField(default=0, help_text='Communication (0-10)'),
        ),
        migrations.AlterField(
            model_name='aievaluation',
            name='conceptual_clarity_score',
            field=models.IntegerField(default=0, help_text='Conceptual Clarity (0-10)'),
        ),
        migrations.AlterField(
            model_name='aievaluation',
            name='creativity_score',
            field=models.IntegerField(default=0, help_text='Creativity (0-10)'),
        ),
        migrations.AlterField(
            model_name='aievaluation',
            name='ease_of_implementation_score',
            field=models.IntegerField(default=0, help_text='Ease of Implementation (0-10)'),
        ),
        migrations.AlterField(
            model_name='aievaluation',
            name='empathy_score',
            field=models.IntegerField(default=0, help_text='Empathy (0-10)'),
        ),
        migrations.AlterField(
            model_name='aievaluation',
            name='final_score',
            field=models.IntegerField(default=0, help_text='Total score out of 100'),
        ),
        migrations.AlterField(
            model_name='aievaluation',
            name='flexible_thinking_score',
            field=models.IntegerField(default=0, help_text='Flexible Thinking (0-10)'),
        ),
        migrations.AlterField(
            model_name='aievaluation',
            name='impactful_score',
            field=models.IntegerField(default=0, help_text='Impact (0-10)'),
        ),
        migrations.AlterField(
            model_name='aievaluation',
            name='sustainable_score',
            field=models.IntegerField(default=0, help_text='Sustainability (0-10)'),
        ),
        migrations.AlterField(
            model_name='aievaluation',
            name='uniqueness_score',
            field=models.IntegerField(default=0, help_text='Uniqueness (0-10)'),
        ),
    ]
