# Generated by Django 5.2.16 on 2026-08-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0011_remove_aievaluation_scalable_justification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aievaluation',
            name='is_top_12',
            field=models.BooleanField(default=False, help_text='Manually selected as Top 12 (national finale)'),
        ),
        migrations.AddField(
            model_name='aievaluation',
            name='zonal_pitch_invited',
            field=models.BooleanField(default=False, help_text='Manually invited to the Zonal Pitch Fest'),
        ),
    ]
